# coding: utf-8

"""
    Easy Redmine API

    https://app.swaggerhub.com/apis/easysoftware/EasySwagger  # noqa: E501

    OpenAPI spec version: 3.1.11
    Contact: support@easyredmine.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import easyapi
from easyapi.api.easy_entity_activity_api import EasyEntityActivityApi  # noqa: E501
from easyapi.rest import ApiException


class TestEasyEntityActivityApi(unittest.TestCase):
    """EasyEntityActivityApi unit test stubs"""

    def setUp(self):
        self.api = easyapi.api.easy_entity_activity_api.EasyEntityActivityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_easy_entity_activities_format_post(self):
        """Test case for easy_entity_activities_format_post

        Create EasyEntityActivity  # noqa: E501
        """
        pass

    def test_easy_entity_activities_id_format_delete(self):
        """Test case for easy_entity_activities_id_format_delete

        Destroy EasyEntityActivity  # noqa: E501
        """
        pass

    def test_easy_entity_activities_id_format_get(self):
        """Test case for easy_entity_activities_id_format_get

        Get EasyEntityActivity  # noqa: E501
        """
        pass

    def test_easy_entity_activities_id_format_put(self):
        """Test case for easy_entity_activities_id_format_put

        Update EasyEntityActivity  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
