# coding: utf-8

"""
    Easy Redmine API

    https://app.swaggerhub.com/apis/easysoftware/EasySwagger  # noqa: E501

    OpenAPI spec version: 3.1.11
    Contact: support@easyredmine.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import easyapi
from easyapi.api.user_api import UserApi  # noqa: E501
from easyapi.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = easyapi.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_format_get(self):
        """Test case for users_format_get

        List of Users  # noqa: E501
        """
        pass

    def test_users_format_post(self):
        """Test case for users_format_post

        Create User  # noqa: E501
        """
        pass

    def test_users_id_format_delete(self):
        """Test case for users_id_format_delete

        Destroy User  # noqa: E501
        """
        pass

    def test_users_id_format_get(self):
        """Test case for users_id_format_get

        Get User  # noqa: E501
        """
        pass

    def test_users_id_format_put(self):
        """Test case for users_id_format_put

        Update User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
