# coding: utf-8

"""
    Easy Redmine API

    https://app.swaggerhub.com/apis/easysoftware/EasySwagger  # noqa: E501

    OpenAPI spec version: 3.1.11
    Contact: support@easyredmine.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import easyapi
from easyapi.api.custom_field_api import CustomFieldApi  # noqa: E501
from easyapi.rest import ApiException


class TestCustomFieldApi(unittest.TestCase):
    """CustomFieldApi unit test stubs"""

    def setUp(self):
        self.api = easyapi.api.custom_field_api.CustomFieldApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_custom_fields_format_get(self):
        """Test case for custom_fields_format_get

        List of CustomFields  # noqa: E501
        """
        pass

    def test_custom_fields_format_post(self):
        """Test case for custom_fields_format_post

        Create CustomField  # noqa: E501
        """
        pass

    def test_custom_fields_id_format_delete(self):
        """Test case for custom_fields_id_format_delete

        Destroy CustomField  # noqa: E501
        """
        pass

    def test_custom_fields_id_format_get(self):
        """Test case for custom_fields_id_format_get

        Get CustomField  # noqa: E501
        """
        pass

    def test_custom_fields_id_format_put(self):
        """Test case for custom_fields_id_format_put

        Update CustomField  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
