# coding: utf-8

"""
    Easy Redmine API

    https://app.swaggerhub.com/apis/easysoftware/EasySwagger  # noqa: E501

    OpenAPI spec version: 3.1.11
    Contact: support@easyredmine.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import easyapi
from easyapi.api.easy_calendar_meeting_api import EasyCalendarMeetingApi  # noqa: E501
from easyapi.rest import ApiException


class TestEasyCalendarMeetingApi(unittest.TestCase):
    """EasyCalendarMeetingApi unit test stubs"""

    def setUp(self):
        self.api = easyapi.api.easy_calendar_meeting_api.EasyCalendarMeetingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_easy_calendar_feed_json_get(self):
        """Test case for easy_calendar_feed_json_get

        List of Easy Meetings  # noqa: E501
        """
        pass

    def test_easy_meetings_format_post(self):
        """Test case for easy_meetings_format_post

        Create EasyMeeting  # noqa: E501
        """
        pass

    def test_easy_meetings_id_format_delete(self):
        """Test case for easy_meetings_id_format_delete

        Destroy EasyMeeting  # noqa: E501
        """
        pass

    def test_easy_meetings_id_format_get(self):
        """Test case for easy_meetings_id_format_get

        Get EasyMeeting  # noqa: E501
        """
        pass

    def test_easy_meetings_id_format_put(self):
        """Test case for easy_meetings_id_format_put

        Update EasyMeeting  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
