# coding: utf-8

"""
    Easy Redmine API

    https://app.swaggerhub.com/apis/easysoftware/EasySwagger  # noqa: E501

    OpenAPI spec version: 3.1.11
    Contact: support@easyredmine.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import easyapi
from easyapi.api.role_api import RoleApi  # noqa: E501
from easyapi.rest import ApiException


class TestRoleApi(unittest.TestCase):
    """RoleApi unit test stubs"""

    def setUp(self):
        self.api = easyapi.api.role_api.RoleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_roles_format_get(self):
        """Test case for roles_format_get

        List of Roles  # noqa: E501
        """
        pass

    def test_roles_id_format_get(self):
        """Test case for roles_id_format_get

        Get Role  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
