# coding: utf-8

"""
    Easy Redmine API

    https://app.swaggerhub.com/apis/easysoftware/EasySwagger  # noqa: E501

    OpenAPI spec version: 3.1.11
    Contact: support@easyredmine.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import easyapi
from easyapi.api.membership_api import MembershipApi  # noqa: E501
from easyapi.rest import ApiException


class TestMembershipApi(unittest.TestCase):
    """MembershipApi unit test stubs"""

    def setUp(self):
        self.api = easyapi.api.membership_api.MembershipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_memberships_id_format_delete(self):
        """Test case for memberships_id_format_delete

        Destroy Membership  # noqa: E501
        """
        pass

    def test_memberships_id_format_get(self):
        """Test case for memberships_id_format_get

        Get Membership  # noqa: E501
        """
        pass

    def test_memberships_id_format_put(self):
        """Test case for memberships_id_format_put

        Update Membership  # noqa: E501
        """
        pass

    def test_memberships_projects_id_memberships_format_get(self):
        """Test case for memberships_projects_id_memberships_format_get

        Retrieve memberships of the Project with specified id  # noqa: E501
        """
        pass

    def test_memberships_projects_id_memberships_format_post(self):
        """Test case for memberships_projects_id_memberships_format_post

        Create a membership in a Project with specified id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
